version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      mantine:
        patterns:
          - "@mantine/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      testing:
        patterns:
          - "@testing-library/*"
          - "vitest"
      eslint:
        patterns:
          - "*eslint*"
      postcss:
        patterns:
          - "postcss*"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "build"

  - package-ecosystem: "gradle"
    directory: "/server"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "build"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "build"
