plugins {
    alias(libs.plugins.micronaut.application)
}

dependencies {
    implementation(project(":domain"))

    runtimeOnly(project(":infrastructure"))

    implementation(libs.micronaut.http.server.netty)
    implementation(libs.micronaut.serde.jackson)
    runtimeOnly(libs.logback.classic)
    runtimeOnly(libs.snakeyaml)

    testImplementation(libs.micronaut.http.client)
}

application {
    mainClass = "gal.conxugal.application.Application"
}

micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("gal.conxugal.*")
    }
}
