package gal.conxugal.domain.auth;

import io.micronaut.core.annotation.Nullable;
import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * A registered user: their identity (email), stored password hash, and role.
 * {@code passwordHash} is never plaintext. {@code id} is generated by the database.
 * {@code lastLoginAt} is {@code null} until the user's first successful login.
 */
@MappedEntity("users")
public record User(
    @Id @GeneratedValue UUID id,
    String email,
    String passwordHash,
    Role role,
    @Nullable Instant lastLoginAt) {

  public User {
    Objects.requireNonNull(id, "id must not be null");
    Objects.requireNonNull(email, "email must not be null");
    Objects.requireNonNull(passwordHash, "passwordHash must not be null");
    Objects.requireNonNull(role, "role must not be null");
  }

  public User(UUID id, String email, String passwordHash, Role role) {
    this(id, email, passwordHash, role, null);
  }

  @Override
  public String toString() {
    return "User[id=%s, email=%s, passwordHash=REDACTED, role=%s, lastLoginAt=%s]"
        .formatted(id, email, role, lastLoginAt);
  }
}
