package gal.conxugal.domain.auth;

import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;
import org.jspecify.annotations.Nullable;

/**
 * A registered user: their identity (email), stored password hash, role, enabled
 * state and creation date. {@code passwordHash} is never plaintext. {@code id} is
 * generated by the database, so it is {@code null} until the account is persisted.
 * {@code lastLoginAt} is {@code null} until the user's first successful login.
 */
@MappedEntity("users")
public record User(
    @Id @GeneratedValue @Nullable UUID id,
    String email,
    String passwordHash,
    Role role,
    boolean enabled,
    Instant createdAt,
    @Nullable Instant lastLoginAt) {

  public User {
    Objects.requireNonNull(email, "email must not be null");
    Objects.requireNonNull(passwordHash, "passwordHash must not be null");
    Objects.requireNonNull(role, "role must not be null");
    Objects.requireNonNull(createdAt, "createdAt must not be null");
  }

  public User(
      @Nullable UUID id, String email, String passwordHash, Role role, boolean enabled,
      Instant createdAt) {
    this(id, email, passwordHash, role, enabled, createdAt, null);
  }

  @Override
  public String toString() {
    return ("User[id=%s, email=%s, passwordHash=REDACTED, role=%s, enabled=%s, "
            + "createdAt=%s, lastLoginAt=%s]")
        .formatted(id, email, role, enabled, createdAt, lastLoginAt);
  }
}
