[versions]
assertj = "3.27.7"
assertjDb = "3.0.0"
bouncyCastle = "1.80"
checkstyle = "13.7.0"
findsecbugs = "1.14.0"
flywayCore = "12.10.0"
jspecify = "1.0.0"
junit = "6.1.1"
micronautPlugin = "5.0.2"
restAssured = "6.0.0"
spotbugs = "4.10.2"
spotbugsGradlePlugin = "6.5.8"
testcontainers = "1.21.3"
wiremock = "3.13.2"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
assertj-db = { module = "org.assertj:assertj-db", version.ref = "assertjDb" }
bouncycastle-provider = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncyCastle" }
findsecbugs-plugin = { module = "com.h3xstream.findsecbugs:findsecbugs-plugin", version.ref = "findsecbugs" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flywayCore" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flywayCore" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
logback-classic = { module = "ch.qos.logback:logback-classic" }
micronaut-data-jdbc = { module = "io.micronaut.data:micronaut-data-jdbc" }
micronaut-data-model = { module = "io.micronaut.data:micronaut-data-model" }
micronaut-data-processor = { module = "io.micronaut.data:micronaut-data-processor" }
micronaut-flyway = { module = "io.micronaut.flyway:micronaut-flyway" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }
micronaut-http-server-netty = { module = "io.micronaut:micronaut-http-server-netty" }
micronaut-jdbc-hikari = { module = "io.micronaut.sql:micronaut-jdbc-hikari" }
micronaut-security-csrf = { module = "io.micronaut.security:micronaut-security-csrf" }
micronaut-security-processor = { module = "io.micronaut.security:micronaut-security-processor" }
micronaut-security-session = { module = "io.micronaut.security:micronaut-security-session" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson" }
micronaut-test-junit5 = { module = "io.micronaut.test:micronaut-test-junit5" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter" }
postgresql = { module = "org.postgresql:postgresql" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "restAssured" }
snakeyaml = { module = "org.yaml:snakeyaml" }
spotbugs-gradle-plugin = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version.ref = "spotbugsGradlePlugin" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }

[plugins]
micronaut-application = { id = "io.micronaut.application", version.ref = "micronautPlugin" }
micronaut-library = { id = "io.micronaut.library", version.ref = "micronautPlugin" }
